---
output: html_document
---

```{r}
library(dplyr)
library(purrr)
library(stringr)
library(readr)
library(gmailr)

gmail_auth(scope = 'full')
#helper functions
get_domain <- function(s){
  str_extract(s, "@[A-Za-z0-9-_.]+") %>% str_replace("@","")
}

get_username <- function(s){
  str_extract(s, "[A-Za-z0-9-_.]+@") %>% str_replace("@","")
}

# get resulting payload
get_info <- function(id) {
  mes <- message(id)
  res = data.frame(
    id = id,
    to = to(mes),
    from = from(mes),
    Date = date(mes),
    subject = subject(mes)
  ) %>%
    mutate(to_name = get_username(to)) %>% 
    mutate(to_domain = get_domain(to)) %>% 
    mutate(from_name = get_username(from)) %>% 
    mutate(from_domain = get_domain(from)) %>%
    mutate(date = dmy_hms(substr(Date, 5, 25), tz = "GMT")) %>%
    mutate(tz_sign = substr(Date, 27, 27)) %>%
    mutate(tz_magn = as.numeric(substr(Date, 28, 29))) %>%
    mutate(date = if_else(tz_sign == "+", date - hours(tz_magn), date + hours(tz_magn))) %>%
    select(id, date, subject, from_name, to_name, to_domain, from_domain)
  
  res
  
}

get_info_robust <- function(id) {
  tryCatch({get_info(id)}, error = function(e){
    data.frame(date = NA, subject = NA,
               id = id, 
               from_name = NA, from_email = NA,
               to_name = NA, to_email = NA, to_domain = NA, from_domain = NA)
  })
}
```

```{r}
# get message ids
n <- 100
system.time({m <- messages(user_id = 'me', num_results = n) %>% gmailr::id()})
system.time({mes <- lapply(m, possibly(message, otherwise = NULL), format = "metadata")})
system.time({
  res <- data_frame(
    id = m[!map_lgl(mes, is.null)],
    to = map_chr(mes, to),
    from = map_chr(mes, from),
    date = as.POSIXct(strptime(map_chr(mes, gmailr::date), "%a, %d %b %Y %X %z")),
    subject = map_chr(mes, subject),
    to_name = get_username(to),
    to_domain = get_domain(to),
    from_name = get_username(from),
    from_domain = get_domain(from)) %>%
  select(id, date, subject, from_name, to_name, to_domain, from_domain)
})
```


t.start2 = Sys.time()
system.time({ res = map_df(m, get_info) })
Sys.time() - t.start2

write_csv(res, "email_data.csv")
```
